services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: registry
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./volume-nexus:/nexus-data
  caddy:
    image: caddy:latest
    container_name: caddy
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volume-caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always
