services:
  registry:
    image: registry:latest
    container_name: registry
    networks:
      - infra-vps
    volumes:
      - ./volume-registry:/var/lib/registry
      - ./auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    networks:
      - infra-vps
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
  caddy:
    image: caddy:latest
    container_name: caddy
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volume-caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volume-caddy/site:/srv
      - ./volume-caddy/caddy_data:/data
      - ./volume-caddy/caddy_config:/config
    networks:
      - infra-vps
    restart: always
  portfolio-2024:
    build:
      context: ./../atelier-heloir/.
      dockerfile: Dockerfile.portfolio-2024
    container_name: portfolio-2024
    networks:
      - infra-vps

networks:
  infra-vps:
